Background: 
    Given User has opened the Simplilearn application
    When User enters correct username "<UserName>"
    And User enters correct password "<Password>"
    And User clicks on Login button

  Scenario: Verify that user is able to see the product details
    Given user has landed on home screen
    When when user do someting
    Then they should be able to see something

  Scenario: Verify that user is able to see the product details
    Given user has landed on home screen
    When when user do someting
    Then they should be anle to see something



